### ISSUE TITLE
please release the new version for update asciidoctor dependency

### ISSUE THREAD

**Issue by teddy-ma** [nanoc/nanoc-asciidoctor#2]
on rubygems.org this gem's RUNTIME DEPENDENCIES is still `asciidoctor ~> 0.1`, 
which makes user to use a old version of asciidoctor, please release a version since you have already update the depency of this repository.

**Comment by mpapis** [comment]
:+1:

**Comment by ddfreyne** [comment]
Oops, apologies for letting this slide. I’ll release it today.

**Comment by ddfreyne** [comment]
This is now done. Thanks for the reminder!
